linters:
  disable-all: true
  enable:
    - gofmt
    - deadcode
    - errcheck
    # TODO(acsaba): readd linters.
    # - golint
    # - ineffassign
    # - unconvert
    # - misspell
    # - govet
run:
  deadline: 5m
  timeout: 5m
