linters:
  disable-all: true
  enable:
    - gofmt
    # TODO(acsaba): readd linters.
    #- deadcode
    #- errcheck
    # - golint
    # - ineffassign
    # - unconvert
    # - misspell
    # - govet
run:
  deadline: 5m
  timeout: 5m
