linters:
  disable-all: true
  enable:
    - gofmt
    - deadcode
    - errcheck
    - golint
    - ineffassign
    - unconvert
    # - misspell
    # - govet
  disable:
    - typecheck
run:
  deadline: 5m
  timeout: 5m
