// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ethereum/go-ethereum/ethclient"
	"gitlab.com/TitanInd/hashrouter/api"
	"gitlab.com/TitanInd/hashrouter/app"
	"gitlab.com/TitanInd/hashrouter/config"
	"gitlab.com/TitanInd/hashrouter/connections"
	"gitlab.com/TitanInd/hashrouter/contractmanager"
	"gitlab.com/TitanInd/hashrouter/events"
	"gitlab.com/TitanInd/hashrouter/interfaces"
	"gitlab.com/TitanInd/hashrouter/lib"
	"gitlab.com/TitanInd/hashrouter/mining"
	"go.uber.org/zap"
)

// Injectors from main.go:

func InitApp() (*app.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	iEventManager := events.NewEventManager()
	miningController := provideMiningController(configConfig, iEventManager)
	connectionsController := provideConnectionController(configConfig, miningController, iEventManager)
	server := provideServer(configConfig, connectionsController)
	client, err := provideEthClient(configConfig)
	if err != nil {
		return nil, err
	}
	sugaredLogger, err := lib.NewLogger()
	if err != nil {
		return nil, err
	}
	sellerContractManager := provideSellerContractManager(configConfig, iEventManager, client, sugaredLogger)
	appApp := &app.App{
		ConnectionsController: connectionsController,
		MiningController:      miningController,
		Server:                server,
		SellerManager:         sellerContractManager,
	}
	return appApp, nil
}

// main.go:

const VERSION = "0.01"

func main() {
	appInstance, err := InitApp()
	if err != nil {
		panic(err)
	}

	appInstance.Run()
}

func provideMiningController(cfg *config.Config, em interfaces.IEventManager) *mining.MiningController {
	return mining.NewMiningController(cfg.Pool.User, cfg.Pool.Password, em)
}

func provideConnectionController(cfg *config.Config, mc *mining.MiningController, em interfaces.IEventManager) *connections.ConnectionsController {
	return connections.NewConnectionsController(cfg.Pool.Address, mc, em)
}

func provideServer(cfg *config.Config, cc *connections.ConnectionsController) *api.Server {
	return api.NewServer(cfg.Web.Address, cc)
}

func provideEthClient(cfg *config.Config) (*ethclient.Client, error) {
	return contractmanager.NewEthClient(cfg.EthNode.Address)
}

func provideSellerContractManager(cfg *config.Config, em interfaces.IEventManager, ethClient *ethclient.Client, logger *zap.SugaredLogger) *contractmanager.SellerContractManager {
	return contractmanager.NewSellerContractManager(logger, em, ethClient, cfg.Contract.Address)
}
